### ISSUE TITLE
request to turn on light group doesn't work if ONE (or more) of the lights is already on

### ISSUE THREAD

**Issue by fermulator** [MycroftAI/skill-homeassistant#37]
Consider the following light group
``` yaml
- platform: group
  name: Main Floor
  entities:
   - light.back_den
   - light.kitchen
   - light.dining_room
   - light.main_front_hall
```

or
``` yaml
- platform: group
  name: Kitchen
  entities:
   - light.kitchen_main
   - light.kitchen_sink
   - light.kitchen_island
   - light.kitchen_counter
```

Let's use the kitchen for this example.

1. "baseline test" -- all lights are off
```
Hey Mycroft, turn on the kitchen lights
```
works!
>> turned on kitchen

2. "subset of lights in a room are on" -- and we want ALL lights in the room on
```
Hey Mycroft, turn on the kitchen lights
or
Hey Mycroft, turn on all of the kitchen lights
```
, doesn't work:
>> no change
>> kitchen lights already on

This is because the "state" of the group is on if any one sub-entity is on.
![Selection_042](https://user-images.githubusercontent.com/6778269/79928627-6f030200-8411-11ea-88b2-6b0c1f7a4ee9.png)

Any suggestions for how to address this scenario?

PS:
3. "subset of lights in a room are on" -- and we want ALL lights in the room off
```
Hey Mycroft, turn off the kitchen lights
```
, works:
>> turned off kitchen
